version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/crud_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      # Telegram bot will use default value from EnvironmentConfig
      # - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME:-crypto_tracker_bot}
      - BINANCE_API_KEY=${BINANCE_API_KEY:-}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY:-}
      - COINBASE_API_KEY=${COINBASE_API_KEY:-}
      - COINBASE_SECRET_KEY=${COINBASE_SECRET_KEY:-}
      # Добавляем CORS настройки
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://frontend:80
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crud_app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        # Для Docker network используем имя сервиса
        - VITE_API_URL=http://localhost:8080/api
        - VITE_WS_URL=ws://localhost:8080/ws
        - VITE_TELEGRAM_BOT_NAME=alg_gor_bot
    ports:
      - "3000:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data: 