-- Fix admin password with correct BCrypt hash generated by the application
UPDATE users 
SET password_hash = '$2a$12$BsmN.j7cmbpSSqRdfz.PaOlMvxFnxNOz00N8UZP5jGa1KnDq17Fui' 
WHERE username = 'admin';

-- Verify the update
SELECT username, SUBSTRING(password_hash, 1, 15) as hash_start FROM users WHERE username = 'admin'; 